# Understanding Window Calculations

## About the Data
In this notebook, we will be working with Facebook's stock price throughout 2018 (obtained using the [`stock_analysis` package](https://github.com/stefmolin/stock-analysis)).

## Interactive Visualizations
If you follow the installation instructions [here](https://github.com/matplotlib/jupyter-matplotlib), you can run the following interactive plot to see what different window calculations look like. This requires you to install `ipyml` and `node.js` and run a few commands from the command line as indicated in the aforementioned link. Note you will need to restart the kernel.

*More information on the `interact()` function can be found [here](https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html).*

In [1]:
%matplotlib widget
from ipywidgets import interact
import matplotlib.pyplot as plt
import pandas as pd

fb = pd.read_csv('data/fb_2018.csv', index_col='date', parse_dates=True)

def window_calculations(df):
    def plot_viz(period=20, window_type='rolling', agg='mean'):
        ax = df.plot(y='close')
        window_func = getattr(df.close, window_type)
        
        if window_type == 'rolling':
            kwargs = {'window': period}
        elif window_type == 'expanding':
            kwargs = {'min_periods': period}
        elif window_type == 'ewm':
            kwargs = {'span': period}
            if agg != 'mean':
                print('Changing to mean')
                agg = 'mean'
        window_func(**kwargs).agg(agg).plot(ax=ax, label=f'{window_type} {period}D {agg}')

        plt.suptitle('Window Calculations on Facebook Closing Price')
        plt.title('(Note: EWM only works with mean)')
        plt.ylabel('price ($)')
        plt.legend()
    
    return plot_viz
interact(
    window_calculations(fb), 
    period=(0, 200, 5), 
    window_type=['rolling', 'expanding', 'ewm'], 
    agg=['sum', 'min', 'max', 'mean']
);

interactive(children=(IntSlider(value=20, description='period', max=200, step=5), Dropdown(description='windowâ€¦

In [6]:
getattr(fb, shape[0])

NameError: name 'shape' is not defined

In [9]:
fb

              open      high       low   close    volume
date
2018-01-02  177.68  181.5800  177.5500  181.42  18151903
2018-01-03  181.88  184.7800  181.3300  184.67  16886563
2018-01-04  184.90  186.2100  184.0996  184.33  13880896
2018-01-05  185.59  186.9000  184.9300  186.85  13574535
2018-01-08  187.20  188.9000  186.3300  188.28  17994726
2018-01-09  188.70  188.8000  187.1000  187.87  12393057
2018-01-10  186.94  187.8900  185.6300  187.84  10529894
2018-01-11  188.40  188.4000  187.3800  187.77   9588587
2018-01-12  178.06  181.4800  177.4000  179.37  77551299
2018-01-16  181.50  181.7500  178.0400  178.39  36183842
2018-01-17  179.26  179.3200  175.8000  177.60  27992376
2018-01-18  178.13  180.9800  177.0800  179.80  23304901
2018-01-19  180.85  182.3700  180.1702  181.29  26826540
2018-01-22  180.80  185.3900  180.4100  185.37  21059464
2018-01-23  186.05  189.5500  185.5500  189.35  25678781
2018-01-24  189.89  190.6600  186.5200  186.55  24334548
2018-01-25  187.95  188.6200  186.6000  187.48  17377740
2018-01-26  187.75  190.0000  186.8100  190.00  17759212
2018-01-29  188.75  188.8400  185.6301  185.98  20453172
2018-01-30  183.01  188.1800  181.8400  187.12  20858556
2018-01-31  188.37  189.8300  185.2200  186.89  43275144
2018-02-01  188.22  195.3200  187.8900  193.09  54211293
2018-02-02  192.04  194.2100  189.9800  190.28  26677484
2018-02-05  186.93  190.6100  180.6100  181.26  33128206
2018-02-06  178.57  185.7700  177.7400  185.31  37758505
2018-02-07  184.15  185.0817  179.9500  180.18  27601886
2018-02-08  181.01  181.8400  171.4815  171.58  38478321
2018-02-09  174.76  176.9000  167.1800  176.11  39887626
2018-02-12  177.06  177.5450  171.8400  176.41  32092133
2018-02-13  175.62  175.9700  173.1000  173.15  21809350
...            ...       ...       ...     ...       ...
2018-11-15  142.33  144.8400  140.8300  143.85  30320280
2018-11-16  141.07  141.7700  137.7700  139.53  37250560
2018-11-19  137.61  137.7500  131.2100  131.55  44362729
2018-11-20  127.03  134.1592  126.8500  132.43  41939475
2018-11-21  134.40  137.1900  134.1300  134.82  25469735
2018-11-23  133.65  134.5000  131.2551  131.73  11886128
2018-11-26  133.00  137.0000  132.7800  136.38  24263640
2018-11-27  135.75  136.6126  133.7100  135.00  20750318
2018-11-28  136.28  136.7899  131.8500  136.76  29847505
2018-11-29  135.92  139.9900  135.6600  138.68  24238713
2018-11-30  138.26  140.9660  137.3600  140.61  25732577
2018-12-03  143.00  143.6799  140.7600  141.09  24819226
2018-12-04  140.73  143.3900  137.1600  137.93  30307400
2018-12-06  133.82  139.7000  133.6700  139.63  28218145
2018-12-07  139.25  140.8700  136.6566  137.42  21195460
2018-12-10  139.60  143.0500  139.0100  141.85  26422173
2018-12-11  143.88  143.8800  141.1000  142.08  20300349
2018-12-12  143.08  147.1900  142.5100  144.50  23696936
2018-12-13  145.57  145.8500  143.1900  145.01  18148610
2018-12-14  143.34  146.0100  142.5100  144.06  21785820
2018-12-17  143.08  144.9200  138.4200  140.19  24333959
2018-12-18  141.08  145.9300  139.8301  143.66  24709084
2018-12-19  141.21  144.9100  132.5000  133.24  57404894
2018-12-20  130.70  135.5700  130.0000  133.40  40297944
2018-12-21  133.39  134.9000  123.4200  124.95  56901491
2018-12-24  123.10  129.7400  123.0200  124.06  22066002
2018-12-26  126.00  134.2400  125.8900  134.18  39723370
2018-12-27  132.44  134.9900  129.6700  134.52  31202509
2018-12-28  135.34  135.9200  132.2000  133.20  22627569
2018-12-31  134.45  134.6400  129.9500  131.09  24625308

[251 rows x 5 columns]